name: Build and publish Python distributions to PyPI
on:
  # push:
  #   branches:
  #     - "main"

  # Only run the `build-status` workflow, on branch `main` completes.  In the job, it checks
  # to make sure the workflow succeeded (using the `if` condition).
  workflow_run:
      workflows: [build-status]
      types: [completed]
      branches: [main]

jobs:
  build-publish:
    name: Build and publish Python distributions to PyPI
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: git checkout repository main
      uses: actions/checkout@v3

    - name: check github reference for tags
      run: |
        echo "github.ref = ${{ github.ref }}, github.ref_type = ${{ github.ref_type }}"
        echo "github.repository = ${{ github.repository }}, github.event_name = ${{ github.event_name }} "

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install pypa/build
      run: python -m pip install build --user

    - name: Build a binary wheel and a source tarball
      run: python -m build --sdist --wheel --outdir dist/ .

    # - name: Publish distribution to Test PyPI
    #   uses: pypa/gh-action-pypi-publish@master
    #   with:
    #     password: ${{ secrets.TEST_PYPI_API_TOKEN }}
    #     repository_url: https://test.pypi.org/legacy/

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}